{
 "title": "General dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Today checks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Watchdog_today_checks_loading_times1{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Today failed checks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Watchdog_today_failed_checks_loading_times1",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_failed_checks_loading_times2",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_failed_checks_loading_times4",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_failed_checks_loading_times5",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_failed_checks_loading_times6",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_failed_checks_loading_times7",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_failed_checks_loading_times8",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_failed_checks_loading_times9",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_failed_checks_loading_times10",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_failed_checks_loading_times11",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_failed_checks_loading_times12",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_failed_checks_loading_times13",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_failed_checks_loading_times14",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_failed_checks_loading_times15",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_failed_checks_loading_times16",
     "legendFormat": "{{site_name}}"
    }
   ]
  },
  {
   "title": "AVG loading time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Watchdog_today_average_loading_time1",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time2",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time4",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time5",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time6",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time7",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time8",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time9",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time10",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time11",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time12",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time13",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time14",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time15",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time16",
     "legendFormat": "{{site_name}}"
    }
   ]
  },
  {
   "title": "AVG loading time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "Watchdog_today_average_loading_time1",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time2",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time4",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time5",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time6",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time7",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time8",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time9",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time10",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time11",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time12",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time13",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time14",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time15",
     "legendFormat": "{{site_name}}"
    },
    {
     "expr": "Watchdog_today_average_loading_time16",
     "legendFormat": "{{site_name}}"
    }
   ]
  }
 ]
}