global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'watchdog'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /api/metrics

  - job_name: 'exchanges'
    scrape_interval: 60s
    static_configs:
      - targets: ['best-obmen.co', 'bitok777.net', 'first-btc.com', 'obmenoff.cc', 'wx.money', 'kz007.org', 'obmen.money', 'exchange.express', 'turrbobot.com', 'appbit.net']
    metrics_path: /api/metrics
